version: '3.8'
services:
  oracle-free:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-free
    ports:
      - "1521:1521"
    environment:
      - WORKLOAD_TYPE=ATP
      - WALLET_PASSWORD=Welcome12345
      - ADMIN_PASSWORD=Welcome12345
    cap_add:
      - SYS_ADMIN
    healthcheck:
      test: ["CMD-SHELL", "docker logs oracle-free | grep 'DATABASE IS READY TO USE!' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s


# Change default password by;
  #./setPassword.sh testpassword inside the container
# Run as system user;
  # sqlplus sys/testpassword@FREEPDB1 as sysdba
  # Create the users/schemas by V1_create_schemas.sql
