CREATE USER USER_SCHEMA IDENTIFIED BY testpassword;
GRANT CREATE SESSION TO USER_SCHEMA;
GRANT CREATE TABLE TO USER_SCHEMA;
GRANT CREATE VIEW TO USER_SCHEMA;
GRANT CREATE USER TO USER_SCHEMA;
GRANT UNLIMITED TABLESPACE TO USER_SCHEMA;
GRANT CREATE ANY TABLE TO USER_SCHEMA;
GRANT CONNECT, RESOURCE, DBA TO USER_SCHEMA;

CREATE USER ADDRESS_SCHEMA IDENTIFIED BY testpassword;
GRANT CREATE SESSION TO ADDRESS_SCHEMA;
GRANT CREATE TABLE TO ADDRESS_SCHEMA;
GRANT CREATE VIEW TO ADDRESS_SCHEMA;
GRANT CREATE USER TO ADDRESS_SCHEMA;
GRANT UNLIMITED TABLESPACE TO ADDRESS_SCHEMA;
GRANT CREATE ANY TABLE TO ADDRESS_SCHEMA;
GRANT CONNECT, RESOURCE, DBA TO ADDRESS_SCHEMA;
